app/models.py
from app import db, login
from flask import current_app
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))
    links = db.relationship('Link', backref='owner', lazy='dynamic')

    def __repr__(self):
        return '<User {}>'.format(self.username)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


class Link(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    url = db.Column(db.String(1000))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return '<Link {}>'.format(self.url)



@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Sign In')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager


db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    return app


from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, url_for
from app.main import bp
from flask_login import login_required
import requests
from bs4 import BeautifulSoup


@bp.route('/', methods=('GET', 'POST'))
@bp.route('/index', methods=('GET', 'POST'))
@login_required
def index():
    result = requests.get('https://www.junomagazine.com')
    src = result.content
    soup = BeautifulSoup(src, 'lxml')

    h3_tag = soup.find_all('h3')
    juno_urls = []
    juno_titles = []
    for link in h3_tag:
        if not "category" in link.a.attrs['href']\
            and not "subscriptions" in link.a.attrs['href']\
            and not "win" in link.a.attrs['href']:
                juno_urls.append(link.a.attrs['href'])
                juno_titles.append(link.a.attrs['title'])
    link_dict = dict(zip(juno_urls, juno_titles))

    result2 = requests.get('https://www.bbc.com/news/uk')
    src = result2.content
    soup = BeautifulSoup(src, 'lxml')

    anchor_tag = soup.find_all('a')
    bbc_urls = []
    for link in anchor_tag:
        if 'class' in link.attrs:
            if 'gs-c-promo-heading' in link.attrs['class']:
                bbc_urls.append(link.attrs['href'])

    result3 = requests.get('https://uk.reuters.com')
    src = result3.content
    soup = BeautifulSoup(src, 'lxml')

    story_div = soup.find_all('div', attrs={'class': 'story-content'})
    reuter_urls = []
    reuter_titles = []
    for link in story_div:
        reuter_urls.append(link.a.attrs['href'])
        reuter_titles.append(link.a.string)
    reuter_dict = dict(zip(reuter_urls, reuter_titles))

    return render_template('index.html', juno_urls=juno_urls,
            juno_titles=juno_titles, link_dict=link_dict, bbc_urls=bbc_urls,
            reuter_dict=reuter_dict)

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% if title %}
    <title>{{ title }} - Aggregator</title>
    {% else %}
    <title>Welcome to Micro-Aggregator</title>
    {% endif %}
  </head>
  <body>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
       <a class="navbar-brand" href="#">Micro-Aggregator</a>
       <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
           <ul class="navbar-nav mr-auto">
               <li class="nav-item active">
                   <a class="nav-link" href="{{ url_for('main.index') }}">
                       Home<span class="sr-only">(current)</span>
                   </a>
               </li>
               {% if current_user.is_anonymous %}
               <li class="nav-item">
                   <a class="nav-link" href="{{ url_for('auth.login') }}">
                       Login
                   </a>
               </li>
               {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">
                        Logout
                    </a>
               </li>
               {% endif %}
           </ul>
       </div>
   </nav>

   {% with messages = get_flashed_messages() %}
   {% if messages %}
   <ul>
       {% for message in messages %}
       <li>{{ message }}</li>
       {% endfor %}
    </ul>
    {% endif %}
   {% endwith %}

   <div class="container">
        {% block content %}{% endblock %}
    </div>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script>
        $(function () {
              $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
  </body>
</html>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
   <h1> Hi, {{ current_user.username.capitalize() }}</h1>
<div class="container">
  <div class="row">

    <div class="col">
      <ul>
        {% for link in bbc_urls %}
        <li>
            <a href="{{ link }}" data-toggle="tooltip" target="_blank" 
                data-placement="bottom" title="{{ link }}">
                {{ link|truncate(45)}}
            </a>
        </li>
        {% endfor %}
      </ul>
    </div>

    <div class="col">
        <ul>
        {% for key, value in link_dict.items() %}
        <li>
            <a href="{{ key }}" data-toggle="tooltip" target="_blank" 
                data-placement="bottom" title="{{ value }}">
                {{ key|truncate(45) }}
            </a>
        </li>
        {% endfor %}
        </ul>
    </div>

  </div>

  <div class="row">

    <div class="col">
      <ul>
        {% for k, v in reuter_dict.items() %}
        <li>
            <a href="{{ k }}" data-toggle="tooltip" target="_blank" 
                data-placement="bottom" title="{{ v }}">
                {{ k|truncate(45) }}
            </a>
        </li>
        {% endfor %}
      </ul>
    </div>
    
  </div>
</div>
{% endblock %}